import subprocess
import json
import sys
import time

def run_mutation_test(test_name, file_path, contents):
    print(f"\n--- Running: {test_name} ---")
    
    process = subprocess.Popen(
        ['./target/debug/omega-mcp-bridge'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1
    )

    time.sleep(0.3)

    call_frame = {
        "jsonrpc": "2.0",
        "method": "tools/call",
        "params": {
            "name": "mutate_code",
            "arguments": {
                "file_path": file_path,
                "contents": contents
            }
        },
        "id": 42
    }

    print(f"Injecting mutation frame to target: {file_path}...")
    process.stdin.write(json.dumps(call_frame) + "\n")
    process.stdin.flush()

    # Dynamic line processing loop: filters out plain text logs, extracts json frames
    while True:
        stdout_line = process.stdout.readline()
        if not stdout_line:
            break
        cleaned = stdout_line.strip()
        if cleaned.startswith("{"):
            print(f"[Immune Response] {cleaned}")
            break

    process.terminate()

# SCENARIO A: Valid Safe Mutation
valid_code = """//! Dynamic metric marker file generated by autopoietic loop
pub fn verify_baseline_frequency() -> f32 {
    16.78
}
"""
run_mutation_test("SCENARIO A: Valid Safe Mutation", "core-engine/src/metric.rs", valid_code)

# SCENARIO B: Invalid Corrupt Mutation
broken_code = """//! Deliberately broken file to test the self-healing immune system
pub fn disrupt_manifold() {
    This is an invalid syntax line that will break cargo compilation.
}
"""
run_mutation_test("SCENARIO B: Toxic Mutation (Forced Syntax Failure)", "core-engine/src/metric.rs", broken_code)
